const userTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_ERROR: 'SIGN_IN_ERROR',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    RESET_PWD_SUCCESS: 'RESET_PWD_SUCCESS',
    RESET_PWD_ERROR: 'RESET_PWD_ERROR',
    RESET_AUTH_FORMS: 'RESET_AUTH_FORMS'
}

export default userTypes