const userTypes = {
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
  SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
  SIGN_UP_USER_START: 'SIGN_UP_USER_START',
  RESET_PWD_START: 'RESET_PWD_START',
  RESET_PWD_SUCCESS: 'RESET_PWD_SUCCESS',
  USER_ERROR: 'USER_ERROR',
  RESET_USER_STATE: ''
};

export default userTypes;
